blog_comment:
    resource: "@BlogBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

post_create:
    path:     /post_create
    defaults: { _controller: BlogBundle:Post:create }

BlogBundle_list:
    path:     /
    defaults: { _controller: BlogBundle:Post:list }

BlogBundle_post:
    path:     /post/{id}
    defaults: { _controller: BlogBundle:Post:post }

save_comment:
    path:     /save_comment
    defaults: { _controller: BlogBundle:Post:saveComment }

BlogBundle_contacts:
    path:     /contacts
    defaults: { _controller: BlogBundle:Pages:contact }

BlogBundle_about:
    path:     /about
    defaults: { _controller: BlogBundle:Pages:about }

login:
    path:     /login
    defaults: { _controller: BlogBundle:User:login }

logout:
    path:     /logout
    defaults: { _controller: BlogBundle:User:logout }

